
IF(ZLIB_REPORTED_HEADER_FOUND OR EXISTS "${ZLIB_INCLUDE_DIRS}/zlib.h")
	IF(NOT ZLIB_REPORTED_HEADER_FOUND)
		MESSAGE(STATUS "Found zlib.h: ${ZLIB_INCLUDE_DIRS}/zlib.h")
		SET(ZLIB_REPORTED_HEADER_FOUND TRUE CACHE INTERNAL "" FORCE)
	ENDIF()
	ADD_DEFINITIONS("-DZLIB_H=\"${ZLIB_INCLUDE_DIRS}/zlib.h\"")
ENDIF()
